### PR TITLE
remove docker caching logic from docker backend

### PR DESCRIPTION
**Pull request by jfmyers9**
[#133638427]

Signed-off-by: James Myers <jmyers@pivotal.io>

### CODE REVIEW

**Comment by Gerg** [comment]
Hey @jfmyers9,

Thanks for the PR. Since the bridge components have changed how they consume their config, this PR was a bit stale.

- @gerg && @aashah

**Comment by ematpl** [comment]
@Gerg || @aashah: Should the Diego team resubmit this PR to reflect those config changes? Are those config changes related to https://www.pivotaltracker.com/story/show/134608685? We'd appreciate more information than just your closing the PR for something that sounds pretty trivial. /cc @SocalNick @utako 

Thanks,
Eric

**Comment by ematpl** [comment]
Oh, I see, https://github.com/cloudfoundry/stager/commit/9e63d982bb5526a7e202a0d591f7de363c5c0e5d reworks this PR. In future, please refer to such a commit manually in your communication about closing the PR, or use [commit message syntax](https://help.github.com/articles/closing-issues-via-commit-messages/) such as "closes #15" to have GitHub automatically close the PR with a reference to the commit.

Thanks,
Eric

**Comment by Gerg** [comment]
Sorry for the confusion, Eric. We tagged the PR in the commit, but we didn't consider what it would look like for people following the thread.

**Comment by ematpl** [comment]
Thanks, @Gerg, not a big deal. I also didn't see your commit tag in the gitbot relabeling and cf-tm-bot reference noise.

Best,
Eric

**Pull request closed without merging**
